version: "3"
services:
  server:
    build:
      context: ./server/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    env_file: ./.env
  db: 
    build: ./db
    env_file: ./.env
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
